package com.src;


import java.awt.MouseInfo;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import WindowsDevices.WindowsServ;
import java.awt.Cursor;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shane
 */
public class MainSpace extends javax.swing.JFrame {
    javax.swing.JPopupMenu conMen = new javax.swing.JPopupMenu();
    private int iWorkNum = 1;
    
    
    /**
     * Creates new form MainSpace
     */
    public MainSpace() {
        initComponents();
        genConMen();
    }
    public void genConMen (){
        javax.swing.JMenuItem genWinServ = new javax.swing.JMenuItem("Windows Server");
        conMen.add(genWinServ);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Workspace = new javax.swing.JTabbedPane();
        panel1 = new java.awt.Panel();
        MainMenu = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        New = new javax.swing.JMenuItem();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        SaveAs = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        Devices = new javax.swing.JMenu();
        Network = new javax.swing.JMenu();
        GenSwi = new javax.swing.JMenuItem();
        GenRou = new javax.swing.JMenuItem();
        Windows = new javax.swing.JMenu();
        GenWinS = new javax.swing.JMenuItem();
        GenWinC = new javax.swing.JMenuItem();
        Linux = new javax.swing.JMenu();
        GenUbunS = new javax.swing.JMenuItem();
        GenUbunC = new javax.swing.JMenuItem();
        GenRHELS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Workspace.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                WorkspaceKeyPressed(evt);
            }
        });

        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        Workspace.addTab("Workspace1", panel1);

        File.setText("File");

        New.setText("New");
        File.add(New);

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        File.add(Open);

        Save.setText("Save");
        File.add(Save);

        SaveAs.setText("Save As");
        File.add(SaveAs);

        MainMenu.add(File);

        Edit.setText("Edit");
        MainMenu.add(Edit);

        Devices.setText("Devices");

        Network.setText("Network");

        GenSwi.setText("Generic Switch");
        Network.add(GenSwi);

        GenRou.setText("Generic Router");
        Network.add(GenRou);

        Devices.add(Network);

        Windows.setText("Windows");

        GenWinS.setText("Generic Windows Server");
        Windows.add(GenWinS);

        GenWinC.setText("Generic Windows Client");
        GenWinC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenWinCActionPerformed(evt);
            }
        });
        Windows.add(GenWinC);

        Devices.add(Windows);

        Linux.setText("Linux");

        GenUbunS.setText("Generic Ubuntu Server");
        Linux.add(GenUbunS);

        GenUbunC.setText("Generic Ubuntu Client");
        Linux.add(GenUbunC);

        GenRHELS.setText("Generic RHEL Server");
        Linux.add(GenRHELS);

        Devices.add(Linux);

        MainMenu.add(Devices);

        setJMenuBar(MainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Workspace, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Workspace)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpenActionPerformed
 
    private void WorkspaceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WorkspaceKeyPressed
        
        
        switch(evt.getKeyCode()){
            
            case KeyEvent.VK_N:
                if(evt.isControlDown()){
                    iWorkNum += 1;
                    Workspace.addTab("Workspace"+ String.valueOf(iWorkNum), new javax.swing.JPanel());
                }
            break;
        }
    }//GEN-LAST:event_WorkspaceKeyPressed

    private void panel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseReleased
        switch(evt.getButton()){
            case 3:
            conMen.setVisible(false);
            System.out.println("Removing the menu");
            break;
        }
    }//GEN-LAST:event_panel1MouseReleased

    private void panel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MousePressed
        System.out.println(evt.getButton());

        switch(evt.getButton()){
            case 3:

            conMen.setVisible(true);
            conMen.setLocation(evt.getXOnScreen(), evt.getYOnScreen());

            System.out.println(evt.getX() + "," + evt.getY());
            System.out.println("tried to make a menu");
            break;
        }
    }//GEN-LAST:event_panel1MousePressed

    private void GenWinCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenWinCActionPerformed
        System.out.println("Tried to make a windows client");
        javax.swing.JButton createdWCli = new javax.swing.JButton("WinC1");
        panel1.add(createdWCli);
    }//GEN-LAST:event_GenWinCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSpace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Devices;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem GenRHELS;
    private javax.swing.JMenuItem GenRou;
    private javax.swing.JMenuItem GenSwi;
    private javax.swing.JMenuItem GenUbunC;
    private javax.swing.JMenuItem GenUbunS;
    private javax.swing.JMenuItem GenWinC;
    private javax.swing.JMenuItem GenWinS;
    private javax.swing.JMenu Linux;
    private javax.swing.JMenuBar MainMenu;
    private javax.swing.JMenu Network;
    private javax.swing.JMenuItem New;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Save;
    private javax.swing.JMenuItem SaveAs;
    private javax.swing.JMenu Windows;
    private javax.swing.JTabbedPane Workspace;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
